In [1]:
import torch
from IPython import display
from d2l import torch as d2l

In [2]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

In [6]:
num_inputs = 784 # 28 * 28
num_outputs = 10

w = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)

In [8]:
# 前置知识
X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
# dim=0 表示“按行方向求和”，也就是对每一列求和。
# dim=1 表示“按列方向求和”，也就是对每一行求和。
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [7]:
# 实现softmax
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp / partition # 这里应用了广播机制

In [13]:
import torch
def cross_entropy(y_hat, y):
    res = y_hat[range(len(y_hat)), y]
    print(f"res---------> {res}")
    return -torch.log(res)

y_hat = torch.tensor([[0.1, 0.7, 0.2],
                      [0.8, 0.1, 0.1]])
y = torch.tensor([1, 0])

loss = cross_entropy(y_hat, y)
print(loss)
print(loss.mean())


res---------> tensor([0.7000, 0.8000])
tensor([0.3567, 0.2231])
tensor(0.2899)
